FIX: Adding missing strings for power_usage_summary
- This adds `fast_charging_title` & `fast_charging_summary` to strings.xml so that it can referred to in the code.

BUG LOGCAT:
FAILED: //packages/apps/Settings:Settings aapt2 link [common]
Outputs: out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/aapt2/package-res.apk out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/gen/proguard.options out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/R.txt
Error: exited with code: 1
Command: out/host/linux-x86/bin/aapt2 link -o out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/aapt2/package-res.apk --enable-compact-entries --manifest out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/manifest_merger/AndroidManifest.xml  --min-sdk-version 34 --target-sdk-version 34 --version-code 34 --version-name  14 --auto-add-overlay -I out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/package-res.apk --product nosdcard -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,en_XC,xxhdpi --preferred-density xxhdpi --no-static-lib-packages --proguard out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/gen/proguard.options --output-text-symbols out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/R.txt -R @out/soong/.intermediates/packages/apps/Settings/Settings/android_common/782bb8d1c3056f27f73d5d6bc57b878a/aapt2/overlay.list
Output:
warn: ignoring density 'xxhdpi-v4' for -c option.
packages/apps/Settings/res/xml/power_usage_summary.xml:62: error: resource string/fast_charging_summary (aka com.android.settings:string/fast_charging_summary) not found.
packages/apps/Settings/res/xml/power_usage_summary.xml:62: error: resource string/fast_charging_title (aka com.android.settings:string/fast_charging_title) not found.
error: failed linking file resources.